name: Java Code Format Check

on:
  pull_request:
    paths:
      - '**/*.java'

jobs:
  java-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Google Java Format jar
        uses: actions/cache@v4
        with:
          path: .cache
          key: google-java-format-v1  # change to v2 as jar version changes below

      - name: Remove corrupt jar (safety net)
        run: rm -f .cache/google-java-format-1.24.0-all-deps.jar || true

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
